# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/settings_global.ui'
#
# Created: Tue Mar  7 19:13:45 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(450, 429)
        Dialog.setMinimumSize(QtCore.QSize(450, 429))
        Dialog.setMaximumSize(QtCore.QSize(450, 429))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 390, 431, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 431, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 391, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cb_ncf = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_ncf.setObjectName(_fromUtf8("cb_ncf"))
        self.gridLayout_2.addWidget(self.cb_ncf, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.cb_ncl = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_ncl.setObjectName(_fromUtf8("cb_ncl"))
        self.gridLayout_2.addWidget(self.cb_ncl, 2, 0, 1, 1)
        self.cb_incr = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_incr.setObjectName(_fromUtf8("cb_incr"))
        self.gridLayout_2.addWidget(self.cb_incr, 1, 1, 1, 1)
        self.cb_gfc = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_gfc.setObjectName(_fromUtf8("cb_gfc"))
        self.gridLayout_2.addWidget(self.cb_gfc, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 381, 101))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sb_after = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sb_after.setMinimum(-1)
        self.sb_after.setObjectName(_fromUtf8("sb_after"))
        self.gridLayout_3.addWidget(self.sb_after, 2, 2, 1, 1)
        self.sb_cloze = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sb_cloze.setMinimum(1)
        self.sb_cloze.setObjectName(_fromUtf8("sb_cloze"))
        self.gridLayout_3.addWidget(self.sb_cloze, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.sb_before = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sb_before.setMinimum(-1)
        self.sb_before.setObjectName(_fromUtf8("sb_before"))
        self.gridLayout_3.addWidget(self.sb_before, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 118, 401, 211))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.le_fl = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_fl.setObjectName(_fromUtf8("le_fl"))
        self.gridLayout.addWidget(self.le_fl, 5, 2, 1, 1)
        self.le_tx = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_tx.setObjectName(_fromUtf8("le_tx"))
        self.gridLayout.addWidget(self.le_tx, 4, 2, 1, 1)
        self.le_model = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_model.setReadOnly(False)
        self.le_model.setObjectName(_fromUtf8("le_model"))
        self.gridLayout.addWidget(self.le_model, 7, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 2)
        self.le_st = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_st.setObjectName(_fromUtf8("le_st"))
        self.gridLayout.addWidget(self.le_st, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.le_og = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_og.setObjectName(_fromUtf8("le_og"))
        self.gridLayout.addWidget(self.le_og, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 2)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 2)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 7, 404, 103))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cb_ns_new = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.cb_ns_new.setObjectName(_fromUtf8("cb_ns_new"))
        self.gridLayout_4.addWidget(self.cb_ns_new, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.cb_ns_rev = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.cb_ns_rev.setObjectName(_fromUtf8("cb_ns_rev"))
        self.gridLayout_4.addWidget(self.cb_ns_rev, 2, 0, 1, 1)
        self.cb_sfc = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.cb_sfc.setObjectName(_fromUtf8("cb_sfc"))
        self.gridLayout_4.addWidget(self.cb_sfc, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(-2, -2, 431, 351))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.sb_before)
        Dialog.setTabOrder(self.sb_before, self.sb_cloze)
        Dialog.setTabOrder(self.sb_cloze, self.sb_after)
        Dialog.setTabOrder(self.sb_after, self.cb_ncf)
        Dialog.setTabOrder(self.cb_ncf, self.cb_ncl)
        Dialog.setTabOrder(self.cb_ncl, self.cb_incr)
        Dialog.setTabOrder(self.cb_incr, self.le_og)
        Dialog.setTabOrder(self.le_og, self.le_st)
        Dialog.setTabOrder(self.le_st, self.le_tx)
        Dialog.setTabOrder(self.le_tx, self.le_fl)
        Dialog.setTabOrder(self.le_fl, self.le_model)
        Dialog.setTabOrder(self.le_model, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Cloze Overlapper Options", None))
        self.cb_ncf.setToolTip(_translate("Dialog", "Don\'t provide any context cues for first cloze item", None))
        self.cb_ncf.setText(_translate("Dialog", "No cues for first item", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Other Cloze Generation Settings</span></p></body></html>", None))
        self.cb_ncl.setToolTip(_translate("Dialog", "Don\'t provide any context cues for last cloze item", None))
        self.cb_ncl.setText(_translate("Dialog", "No cues for last item", None))
        self.cb_incr.setToolTip(_translate("Dialog", "For notes that have multiple clozes revealed per card,<br>gradually build up to full reveal count at the start,<br>and vice-versa in the end", None))
        self.cb_incr.setText(_translate("Dialog", "Gradual build-up/-down", None))
        self.cb_gfc.setToolTip(_translate("Dialog", "Don\'t provide any context cues for first cloze item", None))
        self.cb_gfc.setText(_translate("Dialog", "Don\'t generate full cloze", None))
        self.sb_after.setToolTip(_translate("Dialog", "Number of context cues after the prompt.<br>Set to -1/\'all\' to show all following items as context", None))
        self.sb_after.setSpecialValueText(_translate("Dialog", "all", None))
        self.sb_cloze.setToolTip(_translate("Dialog", "Number of items to prompt for per card", None))
        self.label_12.setText(_translate("Dialog", "Context Before", None))
        self.label_13.setText(_translate("Dialog", "Cloze Prompts", None))
        self.label_14.setText(_translate("Dialog", "Context After", None))
        self.sb_before.setToolTip(_translate("Dialog", "Number of context cues before the prompt.<br>Set to -1/\'all\' to show all previous items as context", None))
        self.sb_before.setSpecialValueText(_translate("Dialog", "all", None))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Default Context Cues and Prompts</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Cloze Generation", None))
        self.le_fl.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog", None))
        self.le_tx.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog", None))
        self.le_model.setToolTip(_translate("Dialog", "Comma-separated list of note types the add-on should be active on", None))
        self.label_2.setText(_translate("Dialog", "<b>Field Names</b>", None))
        self.label_8.setText(_translate("Dialog", "Text", None))
        self.le_st.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog", None))
        self.label_7.setText(_translate("Dialog", "Settings", None))
        self.label_3.setText(_translate("Dialog", "Original", None))
        self.le_og.setToolTip(_translate("Dialog", "These fields can only be renamed through this dialog", None))
        self.label_9.setText(_translate("Dialog", "Full", None))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overlapping Cloze Note Types</span></p></body></html>", None))
        self.label_16.setText(_translate("Dialog", "Names", None))
        self.cb_ns_new.setToolTip(_translate("Dialog", "Disables sibling-burying for cards generated by the add-on,<br>overriding whatever deck options might be set.<br>Only works on Anki desktop", None))
        self.cb_ns_new.setText(_translate("Dialog", "Override sibling-spacing for new overlapping clozes", None))
        self.label_4.setText(_translate("Dialog", "<b>Scheduling</b>", None))
        self.cb_ns_rev.setToolTip(_translate("Dialog", "Disables sibling-burying for cards generated by the add-on,<br>overriding whatever deck options might be set.<br>Only works on Anki desktop", None))
        self.cb_ns_rev.setText(_translate("Dialog", "Override sibling-spacing for overlapping cloze reviews", None))
        self.cb_sfc.setText(_translate("Dialog", "Automatically suspend full cloze cards initially", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "General", None))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:40px; margin-bottom:0px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Credits and License</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-style:italic;\">Cloze Overlapper</span><span style=\" font-size:11pt;\"> is copyright © 2016-2017 </span><a href=\"https://github.com/Glutanimate\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">Aristotelis P.</span></a><span style=\" font-size:11pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">This add-on is licensed under the GNU AGPLv3. </span></p>\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Help and Support</span><span style=\" font-size:11pt;\"> </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 0;\"><li style=\" font-size:11pt;\" style=\" margin-top:12px; margin-bottom:10px; margin-left:35px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/Glutanimate/cloze-overlapper/wiki\"><span style=\" text-decoration: underline; color:#0000ff;\">Cloze Overlapper Wiki</span></a></li>\n"
"<li style=\" font-size:11pt;\" style=\" margin-top:0px; margin-bottom:10px; margin-left:35px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.youtube.com/playlist?list=PL3MozITKTz5Y9owI163AJMYqKwhFrTKcT\"><span style=\" text-decoration: underline; color:#0000ff;\">Video Tutorials on YouTube</span></a></li>\n"
"<li style=\" font-size:11pt; text-decoration: underline;\" style=\" margin-top:0px; margin-bottom:10px; margin-left:35px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://anki.tenderapp.com/discussions/add-ons/9407-cloze-overlapper-official-thread\"><span style=\" color:#0000ff;\">Official Support Thread</span></a></li></ul></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Help and Info", None))

